export default class Contact {
  constructor(firstName, lastName, email, phone, company, position) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.phone = phone;
    this.company = company;
    this.position = position;
  }
}

const firstNames = [
  "Aksel",
  "Anders",
  "Anna",
  "Anne",
  "Benjamin",
  "Camilla",
  "Cecilie",
  "Christian",
  "Christina",
  "Daniel",
  "David",
  "Emil",
  "Emma",
  "Frederik",
  "Freja",
  "Hannah",
  "Ida",
  "Isabella",
  "Jakob",
  "Jens",
  "Jonas",
  "Josefine",
  "Julie",
  "Laura",
  "Liam",
  "Lukas",
  "Malik",
  "Malthe",
  "Maja",
  "Maria",
  "Mathias",
  "Mia",
  "Mikkel",
  "Mille",
  "Nikolaj",
  "Noah",
  "Oliver",
  "Oscar",
  "Pernille",
  "Rasmus",
  "Sarah",
  "Signe",
  "Silke",
  "Simon",
  "Sofia",
  "Sophie",
  "Thea",
  "Thomas",
  "Tobias",
  "Victoria",
  "William",
  "Laura",
  "Amalie",
  "Anton",
  "Emilie",
  "Felix",
  "Frederikke",
  "Helene",
  "Henrik",
  "Jesper",
  "Joachim",
  "Kasper",
  "Kristian",
  "Kristine",
  "Lasse",
  "Lene",
  "Louise",
  "Mads",
  "Maj",
  "Mikkel",
  "Mille",
  "Nanna",
  "Natasja",
  "Nicolai",
  "Niklas",
  "Nikoline",
  "Nina",
  "Oline",
  "Pernille",
  "Rikke",
  "Sandra",
  "Sidsel",
  "Sofie",
  "Søren",
  "Stine",
  "Svend",
  "Thomas",
  "Tina",
  "Trine",
  "Tina",
  "Vibeke",
  "Victoria",
  "Zara",
];

const lastNames = [
  "Andersen",
  "Nielsen",
  "Jensen",
  "Hansen",
  "Pedersen",
  "Mortensen",
  "Christensen",
  "Larsen",
  "Rasmussen",
  "Petersen",
  "Madsen",
  "Olsen",
  "Knudsen",
  "Kristensen",
  "Thomsen",
  "Jakobsen",
  "Johansen",
  "Olesen",
  "Mikkelsen",
  "Eriksen",
  "Hoffmann",
  "Jepsen",
  "Mogensen",
  "Haugaard",
  "Holm",
  "Vestergaard",
  "Kjeldsen",
  "Sørensen",
  "Foged",
  "Lund",
  "Krogh",
  "Andreasen",
  "Simonsen",
  "Villadsen",
  "Hald",
  "Jørgensen",
  "Bach",
  "Poulsen",
  "Mortensen",
  "Lorentzen",
  "Berg",
  "Hedegaard",
  "Lassen",
  "Winther",
  "Bisgaard",
  "Klausen",
  "Højbjerg",
  "Lund",
  "Dam",
  "Bæk",
  "Lind",
  "Juhl",
  "Bjerre",
  "Møller",
  "Mortensen",
  "Eskildsen",
  "Poulsen",
  "Christensen",
  "Søgaard",
  "Dahl",
  "Lauridsen",
  "Dinesen",
  "Bech",
  "Henriksen",
  "Vestergaard",
  "Ludvigsen",
  "Ebbesen",
  "Svendsen",
  "Lauritsen",
  "Høj",
  "Mølgaard",
  "Nygaard",
  "Jessen",
  "Lange",
  "Eriksen",
  "Frederiksen",
  "Holm",
  "Kristensen",
  "Jensen",
  "Højbjerg",
  "Henriksen",
  "Kristensen",
  "Lund",
  "Larsen",
  "Mikkelsen",
  "Mathiesen",
  "Mortensen",
  "Nielsen",
  "Olesen",
  "Pedersen",
  "Poulsen",
  "Rasmussen",
  "Sørensen",
];

const companies = [
  "A.P. Møller-Mærsk",
  "Novo Nordisk",
  "Danske Bank",
  "Vestas",
  "Carlsberg",
  "DONG Energy",
  "Maersk Oil",
  "ISS",
  "Jyske Bank",
  "Sydbank",
  "TDC",
  "Pandora",
  "Nordea",
  "Rockwool",
  "DSV",
  "Coloplast",
  "GN Store Nord",
  "Chr. Hansen",
  "Genmab",
  "Tryg",
  "Demant",
  "Ambu",
  "Bang & Olufsen",
  "Topdanmark",
  "FLSmidth",
  "Grundfos",
  "Ørsted",
  "Københavns Lufthavne",
  "NKT",
  "Alm. Brand",
  "William Demant",
  "NKT",
  "Bavarian Nordic",
  "FLSmidth",
  "Solar",
  "SimCorp",
  "Lundbeck",
  "D/S Norden",
  "COWI",
  "Skjern Bank",
  "Glunz & Jensen",
  "Mols-Linien",
  "Nordfyns Bank",
  "RTX",
  "Nørresundby Bank",
  "Nykredit",
  "Alm. Brand Bank",
  "Eniig",
  "Fibia",
  "Nets",
  "H. Lundbeck",
  "Børsen",
  "Nationalbanken",
  "DANIDA",
  "SAS",
  "Ørsted",
  "Kopenhagen Fur",
  "DSB",
  "Mærsk",
  "BC Hospitality Group",
  "Daloon",
  "East Asiatic Company",
  "GN",
  "Mærsk Line",
  "Mærsk Drilling",
  "Tuborg",
  "Faxe Kondi",
  "Danfoss",
  "Rambøll",
  "Rational",
  "LEGO Group",
  "Netcompany",
  "Danish Crown",
  "Arla Foods",
  "Dansk Supermarked",
  "Lidl",
  "Flying Tiger Copenhagen",
  "IC Group",
  "Bestseller",
  "Royal Unibrew",
  "DLG",
  "Lantmännen Unibake",
  "Kopenhagen Fur",
  "Chr. Hansen",
  "Arla Foods",
  "Velux",
  "SKOV",
  "ROCKWOOL",
  "Cembrit",
  "LEGO",
  "Coloplast",
  "Foss",
  "LM Wind Power",
  "Ramboll",
  "Nilfisk",
  "VELUX",
];

const positions = [
  "Softwareudvikler",
  "Webudvikler",
  "Frontend-udvikler",
  "Backend-udvikler",
  "Full-stack udvikler",
  "UI/UX-designer",
  "Produktchef",
  "Projektleder",
  "Dataforsker",
  "Dataanalytiker",
  "Maskinlæringsingeniør",
  "DevOps-ingeniør",
  "Systemadministrator",
  "Netværksingeniør",
  "Databaseadministrator",
  "Kvalitetssikringsingeniør",
  "Forretningsanalytiker",
  "Salgschef",
  "Marketingchef",
  "Indholdsforfatter",
  "Grafisk designer",
  "Kundesupportspecialist",
  "HR-chef",
  "Finansanalytiker",
  "Regnskabsfører",
  "Juridisk rådgiver",
  "Driftsleder",
  "IT-direktør",
  "Teknologidirektør",
  "Administrerende direktør",
];

export const createRandomContact = () => {
  const generatePhoneNumber = () => {
    let phoneNumber = "+45 ";

    for (let i = 0; i < 8; i++) {
      phoneNumber += Math.floor(Math.random() * 10).toString();
      if (i === 1 || i === 3 || i === 5) {
        phoneNumber += " ";
      }
    }

    return phoneNumber;
  };

  const getRandomEmail = (firstName, lastName) => {
    const domains = ["gmail.com", "yahoo.com", "outlook.com"];
    const randomDomainIndex = Math.floor(Math.random() * domains.length);
    return `${firstName.toLowerCase()}.${lastName.toLowerCase()}@${
      domains[randomDomainIndex]
    }`;
  };

  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
  const company = companies[Math.floor(Math.random() * companies.length)];
  const position = positions[Math.floor(Math.random() * positions.length)];

  return new Contact(
    firstName,
    lastName,
    getRandomEmail(firstName, lastName),
    generatePhoneNumber(),
    company,
    position
  );
};
